# golangci-lint configuration for DSL Onboarding POC
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  # Exclude directories from linting
  exclude-dirs:
    - vendor
    - .claude

  # Exclude rules for specific paths/linters
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    # Exclude linting of generated files
    - path: \.pb\.go$
      linters:
        - all

    # Ignore long lines in comments
    - linters:
        - revive
      text: "line is \\d+ characters"
      source: "^\\s*//.*$"

  max-issues-per-linter: 20
  max-same-issues: 2
  new: false
  uniq-by-line: true

linters:
  disable-all: false
  enable:
    # Critical - potential bugs and errors
    - errcheck # Check for unchecked errors
    - govet # Reports suspicious constructs (includes shadow detection)
    - staticcheck # Static analysis checks
    - typecheck # Type-check code
    - errorlint # Find code that causes problems with Go 1.13+ error wrapping

    # Code quality - maintainability
    - gosimple # Simplify code
    - ineffassign # Detect ineffectual assignments
    - unused # Check for unused constants, variables, functions, and types
    - dupl # Check for duplicate code (major duplications only)
    - goconst # Find repeated strings that could be constants

    # Formatting and style
    - gofmt # Check formatting
    - goimports # Check import formatting
    - misspell # Find commonly misspelled English words

    # Security (minimal)
    - gosec # Only major security issues

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Println
      - fmt.Printf
      - fmt.Print
      - log.Printf
    # Ignore test helper errors
    ignore: fmt:.*,log:.*

  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: dsl-ob-poc

  misspell:
    locale: US
    ignore-words:
      - cancelled # British spelling used in our domain

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: true
      - name: var-naming
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G201 # SQL string formatting (common in our queries)
      - G301 # Poor file permissions (not critical for POC)
      - G306 # Poor file permissions on write
    config:
      G306: "0644"
    # Only flag high severity issues
    severity: high

  goconst:
    min-len: 4
    min-occurrences: 4
    # Ignore short common strings
    ignore-tests: true

  dupl:
    threshold: 200

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - unnamedResult
      - paramTypeCombine
      - ifElseChain
      - nestingReduce
      - sprintfQuotedString

  errorlint:
    errorf: true
    asserts: true
    comparison: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

severity:
  default-severity: warning
  case-sensitive: false
